# RTAB-Map 노드의 파라미터 설정 파일
rtabmap:
  ros__parameters:
    # --- 기본 설정 ---
    frame_id: "base_link"             # 로봇의 기준 좌표계
    use_sim_time: true                # 시뮬레이션 시간 사용 (Gazebo 사용 시 필수)
    subscribe_depth: true             # 뎁스 이미지 구독 활성화
    subscribe_scan: true              # 2D LiDAR 스캔 구독 활성화
    
    # --- 맵핑 품질 관련 ---
    queue_size: 100                   # 처리할 메시지 큐 크기
    Grid/RangeMax: 12.0               # 2D 그리드 맵 생성 시 최대 레이저 거리
    
    # --- 위치 추정 및 루프 클로징 관련 ---
    Reg/Strategy: "1"                 # 위치 보정 전략 (0: Visual, 1: ICP) 1로 설정하여 LiDAR 우선
    Icp/VoxelSize: 0.05               # ICP 계산 시 포인트 클라우드를 다운샘플링할 크기
    Icp/MaxCorrespondenceDistance: 0.2 # ICP 계산 시 대응점 탐색 최대 거리

# 시각화 노드 파라미터 (동일하게 설정)
rtabmap_viz:
  ros__parameters:
    frame_id: "base_link"
    use_sim_time: true
    subscribe_scan: true
    subscribe_odom: true