### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 20.0                 # 예측과 센서 데이터를 통한 보정(수정)을 포함한 전체 필터링 사이클이 얼마나 자주 실행될지를 결정
        two_d_mode: true                # 2D 모드 활성화 (로봇이 주로 평면에서 움직이는 경우)
        publish_acceleration: false     # 가속도 데이터를 퍼블리시할지 여부(시스템 부하를 낮추기 위해 보통 false로 설정)
        publish_tf: true                # TF 변환을 퍼블리시할지 여부   

        map_frame: map                  # GPS나 SLAM(지도 생성)을 통해 얻어지는, 오차가 수정된 전역적인 기준점
        odom_frame: odom                # Defaults to "odom" if unspecified
        base_link_frame: base_footprint  # Defaults to "base_link" (base_link 대신 base_footprint를 쓰는 것은 로봇의 중심을 바닥면에 투영한 좌표계를 사용하겠다는표현)
        world_frame: odom               # EKF 인스턴스가 생성할 좌표 변환의 기준(world)

        odom0: odom                     # 휠 오도메트리 데이터 토픽 이름
        odom0_config: [false, false,  false,    # 어떤 값을 필터에 융합할지 선택하는 15칸짜리 스위치 배열입니다.
                       false, false, false,     # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
                       true, true, false,
                       false, false, true,
                       false, false, false]

        imu0: imu                       # IMU 데이터 토픽 이름
        imu0_config: [false, false, false,      # 어떤 값을 필터에 융합할지 선택하는 15칸짜리 스위치 배열입니다.
                      true,  true,  true,       # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
                      false, false, false,
                      false,  false,  true,
                      true,  false,  false]
                      
        imu0_differential: false     # IMU 데이터를 차분적으로 처리할지 여부 (보통 false로 설정)


        # 고급 설정
        # 각 센서 데이터의 잡음 특성을 정의하는 매개변수
        # 각 값은 상태 변수에 대한 측정 잡음의 분산을 나타
        # 공간적 오차 공분산 행렬 (Q)     
        process_noise_covariance: [0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.06, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.03, 0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.03, 0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.06, 0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.025, 0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.025, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01, 0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01, 0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01, 0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01, 0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]
        # 측정 잡음 공분산 행렬 (R)

        initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9]